# Generated by Django 4.0 on 2021-12-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=50)),
                ('unidad_medida', models.CharField(max_length=3)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=7)),
                ('is_light', models.BooleanField()),
                ('is_alcohol', models.BooleanField()),
                ('sabor', models.CharField(max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Cigarrillos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('sabor', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Golosinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('unidad_medida', models.CharField(max_length=3)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=7)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('is_light', models.BooleanField()),
                ('is_free_gluten', models.BooleanField()),
            ],
        ),
    ]
